import requests 
import time
from PIL import Image,ImageEnhance,ImageFile
from config import Hf_API_KEY

Models= [

"black-forest-labs/FLUX.1-schnell",

"stabilityai/stable-diffusion-xl-base-1.0",

"stable-diffusion-v1-5/stable-diffusion-v1-5",

"CompVis/stable-diffusion-v1-4",
]

Headers = {"Authorization": f"Bearer {Hf_API_KEY}", "accept": "image/png"}
def generate_image(prompt):
    payload ,last_err= {"inputs": prompt}, None
    for model in Models:
        url = f"https://router.huggingface.co/hf-inference/models/{model}"
        for _ in range(3):
            r = requests.post(url, headers=Headers, json=payload, timeout=60)
            ct = (r.headers.get("content-type") or "").lower() 
            if r.status_code == 503 and "application/json" in ct:
                try:
                    wait_s = int(r.json().get("estimated_time",5))
                except Exception:
                    wait_s = 5
                    time.sleep(wait_s+1)
                    continue
            if r.status_code == 200 and "application/json" not in ct:
                try:
                    return Image.open(bytesIO(r.content)).convert("RGB")
                except Exception as e:
                    last_err = (f"failed with sttus code 200 : can't load the image {e}")
                    break
            try:
                body= r.json() if "application/json" in ct else r.text
            except Exception:
                body = r.text
            last_err = (f"failed with status code {r.status_code} : {body}")
            break
        raise Exception(f"request failed with status code 500: or {last_err}")
def post_process_image(image):
    image = ImageEnhance.Brightness(image).enhance(1.2)
    image = ImageEnhance.Contrast(image).enhance(1.3)
    return image.filter(ImageFilter.GaussianBlur(radius=2))
 def main():
    print("welcome to the image post processing program")
    print("in this program image is generated by text prompt and the post processed")
    print("type exit or q to quit \n")
    while True:
        user_input=input("please enter the prompt to generate the image")
        if user_input.lower() == "exit":
            print("goodbye")
            break
        try:
            print("\ngenerating the image")
            image= generate_image(user_input)
            
