print("please enter the marks of each subject")
math=int(input("math-"))
english=int(input("english-"))
hindi=int(input("hindi-"))
science=int(input("science-"))
total=(math+hindi+english+science)
print("total marks are- ",total)
perc=int((total/400)*100)
print(perc,"%")